### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by pbies** [in3rsha/bitcoin-utxo-dump#46]
For height 871220 now the python script gives error:

`./utxo-live.py

Rendering the 660 utxos in 871220.dat...

This should take between 10 and 30 min...

Traceback (most recent call last):
  File "/mnt/c/2/./utxo-live.py", line 317, in <module>
    utxos = get_UTXOs(fin, batch_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/2/./utxo-live.py", line 188, in get_UTXOs
    utxos.append(get_UTXO(fin))
                 ^^^^^^^^^^^^^
  File "/mnt/c/2/./utxo-live.py", line 156, in get_UTXO
    script_b = fin.read(data_size)
               ^^^^^^^^^^^^^^^^^^^
MemoryError`

**Comment by in3rsha** [comment]
I think you may have the wrong repo. There is no `utxo-live.py` file in this repo.
